sudo: required
language: java
notifications:
  email: false
jdk:
- openjdk11
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - VERSION=latest
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: thKKscnXm7+SYWfu1kx0zwQxortmwHCaSnuy+tDFRpuc58nZzeJDF9pZnLTtEg14MDdzl98qBaRnTnoLPSNVV/cBhPB/PMV2SGnr5IBLrj4/QgY13EjYYFIlbif/IBk2RH+mWuSg25o4LHsnZ+qZjwenWWXu3RMwsZkfvaGvhQuO8b1zMGWr/wg+/uKHSEQi0aLriYZIhquJj7ys7x3lFR01ixOs72lV+CK5x/LtgBb/HAI6X0xTf4EYgGDidl9RR4O/H5MlsDVBzuEin7+RSm10gh3UhbJCFhxC55E4P1MvYDuq53RBGqV9kbEfdMtcpY5QNe6eyNAPq0Pre/K5fx2MBARL6jef9Or56WQ/qA75yS2ZR+vQbJoj9C8wmPi2KK8TWODSZOnAvYrDtiS7GPM16ApcKS4vnkXrPK0vMycabBIY7H5uvJyR9AjMhFi6eCWFgAUCW2KEUEk5/4pAsJowEDMS+LPLIxPny/bWBDB+heBsRj5qvT7Xx3igLXXYwtgJSSji2C+O7IJpLlW2VaZqvlG9j+niir1TSuRrbf6bneIT0XNbZg8nTOs9FmoEebSrbU4v6O3tLA8uLn30t5kb7mm93rxWTkk/0PqgkDjxeiAM5cysdIjV44nlKRZh1xUulmRQOmuOAU0Y5/WielTWRVsqzWYUMYJRjTD9AUQ=
  - secure: SdNGyfNoAeqN3B3Exv5zql7U/WXWCOHROvCCh2u34nwh28QlsFwC3eXYvuTBf7pLY3qhoDFRfd9yYw5lyur4C/883CGWJjNsM+kpwVz14PGSWhJ0a3/PD8AQRRfMmgZ5pyikXm1U+GJ9l2de65j5EomWTdth4E6JqNb0EgY/no0anF2mVvFj+PUcKju0p1QatNUCcbwdi1qlC/SGCvTXvqH/Qhie2eeLwtUe1pQcgPXq1CHB81KT5D391tHRE59ttVWtOIF2td5X1R17eL9xYlnGW7U9TXMqQwLbM5/lokJBVCeS8vWxpq4PJHjwG5NUnNmgf8he/w+phxIeK2+tQP5LTm+RYlpmuY/+fJB73Wr1Q14LxQZC3A6kmB/9mCYvRflF+CyD/II0XBRgOhF7VNaUw1qiOD+z8svYgFA76pjbFiIK4PVwDyyWIjdCgW0u0xu8NQUQG9zMLv9BiuJHRSvH/jLj1WbFdVgxpFS6xHvPzknGkwNnrK0T2hbkCXir/8zBmXjTtqLAWuDjVh1xvUXahO/4tqkP99//ijkMxQFL98kTwNZaAef5r7C+o3JTH0eonLPyCvofQkjGsDl8JLLM0DE2P2F2m1S1jmXcnSEAYRGQIGJXrK4KFckIlKUYKFQqkOpE9zqunOZJE2cHEZNFyDtgUd7jzHLYA4uaRk0=
