sudo: required
language: java
notifications:
  email: false
jdk:
- openjdk11
services:
- docker
script:
- ".travis/build.sh $VERSION $COMMIT"
env:
  global:
  - VERSION=latest
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: XvdsCRKUXysM3RotYwJ36hBw2kiqFE0Gmtv+JTn2j9tDf2Ar6Fq6XAhqN6QQIatw05szsV7VlPwSJhhafXaRG3PiQ09t328/clXgjoXu+T8oD8KXY+n6UGfOVUT2GZIn/W/qGxffig7LzoZTCBvkkzYcWIR9zJ2OZZMXMjAKnaHPSCPLYk1t3lBuFkFVsv5En3SjF9vAHxB9YW1cuOgE3miSp8Xu3sVMLgB1ntckBOufmHLxN/3+hDpYY4eE3C1v6G83xPNkgb9AmaMxPf0rhZE0QwVLieFgm9T1+XzPkpoznawfXPBZQ3b2yg4cZqgTR3sMrZZAYWQxWbUi929ZsD1dVGymEmSo0JrgGBLnOnAueEqndpzs6dpKhyzwJOi6WZkUdErsht7g8FgqnBrx0aNMlKmU6zIrkqNPpSG9+NtipgYniQ/oRfN3/mysA5FA1xgHc6qMdW0dDpuWniJfy8UxdtdOycWFvhIun4OHCPDT1Nxxjr17yTSm9piy9pno5SquKFpYEjmkf3qlgnUaE1JBmCIz2rQINQ6shs5eMZfQeYD7c8S5UsnYcbEcTep6yOcnShrGdgnY5Tuadf8CrsTUP7HWCZ2ACNDKun1X5GUy1TXZt/y1Vwm431MFJ7tNIRxzeLUQUoTXAaM2I6yorAOVrBDYgIUeUvmjUiz+jzM=
  - secure: YdAMVPmUDgrT6cd9kDgNATE4e9TwN57GY8CABeLMcMRos3nwsfofEgkCO/1plgBgEnSRBQYKTjy48cb8Z2iot2PZJHfJpFD1O2Ku5nRLURgvT8NtBuWwA0B+VTuXjK7Ncx2dRic0E7EugMPpc4EaICELQHafFkoAoeCFQIBW67YCipWG14T7b4Um9/q38GGB7/aJ4K6Sfq50ZZorAGLJG4GBjp2s1Kfsb2OtD1wGjSyRzH0qw+6LUX0aLTfyZ+tklPs0On35MH/24eY3b/BQ2/Dzf1ZmMr1GiGG6WkQyBDpVG6pjOPD9EdXEnZGZ+xVnCsRJZB5vJTEKMBE6QVugHJJkZUNyIvezGFGw6DutbrThpk+C8o0xgPCdp6ZNapgqCLj7lTMhDUjL09fcYGkYmgAclL37MKOA5glsnqwt5slX2EncsXHEGLU3GmkIuKu3lOga9tAmDfGN4xUu6JQ9/zm+NuLnVoy4byI0bUgFexN4S8YAgKXvxA2/0LEVKA7fnDBwOIvbrGKPpp9F50711H1xay57dNR2y10vjBPgUogZDI4KBTyXyADoiK5w5jwmExA0vB+X3OoRkulc8MiE+b0jG9IkQ1WUEZeuOKBzWxJ4aTFMBnEaSFgRccrY7c59DIyq9ixVpb5RbFpzx8Gwu0fiV1qr1TOEUi2onKrq000=
