apiVersion: v1
kind: Service
metadata:
  name: tenant-client
  labels:
    app: test-clients
    client: tenant-client
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app: test-clients
    client: tenant-client
  type: ClusterIP
